#include "server/info.h"
#include <iostream>

void print_eula()
{
  std::cout << "===============================     ATTENTION     ==============================" << std::endl;
              // vvv 80 character width vvv
              /*12345678901234567890123456789012345678901234567890123456789012345678901234567890*/
  std::cout << "The author(s) of this software wish to make it clear that it was created" <<
  std::endl << "by AMATUER developers, without the experience, resources, nor manpower usually" <<
  std::endl << "expected in such a product. As such, it DOES NOT and could not have had the" <<
  std::endl << "usual amount of testing and security-checking typical in professional software." <<
  std::endl <<
  std::endl << "Use this software AT YOUR OWN RISK. Be aware of, and plan for the dangers" <<
  std::endl << "inherent in any piece of sortware that opens connections to the internet," <<
  std::endl << "especially an amatuer one such as this." <<
  std::endl << std::endl;
  
  std::cout << "This work is distributed under the Apache License 2.0. Relevant terms for the" <<
  std::endl << "use of this software include sections 4, 7, and 8. Please read the whole" <<
  std::endl << "license, a copy of which was included with the Source for this software, and" <<
  std::endl << "further copies can be obtained at http://www.apache.org/licenses/LICENSE-2.0" <<
  std::endl << std::endl;
              // vvv 80 character width vvv
              /*12345678901234567890123456789012345678901234567890123456789012345678901234567890*/
  std::cout << "            ====== Relevant sections from Apache License 2.0 ======             " <<
  std::endl << "(note that this Work does in fact include a NOTICE file, as mentioned in s4.d)" <<
  std::endl <<
  std::endl << "4. Redistribution. You may reproduce and distribute copies of the" <<
  std::endl << "   Work or Derivative Works thereof in any medium, with or without" <<
  std::endl << "   modifications, and in Source or Object form, provided that You" <<
  std::endl << "   meet the following conditions:" <<
  std::endl <<
  std::endl << "   (a) You must give any other recipients of the Work or" <<
  std::endl << "       Derivative Works a copy of this License; and" <<
  std::endl <<
  std::endl << "   (b) You must cause any modified files to carry prominent notices" <<
  std::endl << "       stating that You changed the files; and" <<
  std::endl <<
  std::endl << "   (c) You must retain, in the Source form of any Derivative Works" <<
  std::endl << "       that You distribute, all copyright, patent, trademark, and" <<
  std::endl << "       attribution notices from the Source form of the Work," <<
  std::endl << "       excluding those notices that do not pertain to any part of" <<
  std::endl << "       the Derivative Works; and" <<
  std::endl <<
  std::endl << "   (d) If the Work includes a \"NOTICE\" text file as part of its" <<
  std::endl << "       distribution, then any Derivative Works that You distribute must" <<
  std::endl << "       include a readable copy of the attribution notices contained" <<
  std::endl << "       within such NOTICE file, excluding those notices that do not" <<
  std::endl << "       pertain to any part of the Derivative Works, in at least one" <<
  std::endl << "       of the following places: within a NOTICE text file distributed" <<
  std::endl << "       as part of the Derivative Works; within the Source form or" <<
  std::endl << "       documentation, if provided along with the Derivative Works; or," <<
  std::endl << "       within a display generated by the Derivative Works, if and" <<
  std::endl << "       wherever such third-party notices normally appear. The contents" <<
  std::endl << "       of the NOTICE file are for informational purposes only and" <<
  std::endl << "       do not modify the License. You may add Your own attribution" <<
  std::endl << "       notices within Derivative Works that You distribute, alongside" <<
  std::endl << "       or as an addendum to the NOTICE text from the Work, provided" <<
  std::endl << "       that such additional attribution notices cannot be construed" <<
  std::endl << "       as modifying the License." <<
  std::endl <<
  std::endl << "   You may add Your own copyright statement to Your modifications and" <<
  std::endl << "   may provide additional or different license terms and conditions" <<
  std::endl << "   for use, reproduction, or distribution of Your modifications, or" <<
  std::endl << "   for any such Derivative Works as a whole, provided Your use," <<
  std::endl << "   reproduction, and distribution of the Work otherwise complies with" <<
  std::endl << "   the conditions stated in this License." <<
  std::endl <<
  std::endl <<
  std::endl << "7. Disclaimer of Warranty. Unless required by applicable law or" <<
  std::endl << "   agreed to in writing, Licensor provides the Work (and each" <<
  std::endl << "   Contributor provides its Contributions) on an \"AS IS\" BASIS," <<
  std::endl << "   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or" <<
  std::endl << "   implied, including, without limitation, any warranties or conditions" <<
  std::endl << "   of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A" <<
  std::endl << "   PARTICULAR PURPOSE. You are solely responsible for determining the" <<
  std::endl << "   appropriateness of using or redistributing the Work and assume any" <<
  std::endl << "   risks associated with Your exercise of permissions under this License." <<
  std::endl <<
  std::endl <<
  std::endl << "8. Limitation of Liability. In no event and under no legal theory," <<
  std::endl << "   whether in tort (including negligence), contract, or otherwise," <<
  std::endl << "   unless required by applicable law (such as deliberate and grossly" <<
  std::endl << "   negligent acts) or agreed to in writing, shall any Contributor be" <<
  std::endl << "   liable to You for damages, including any direct, indirect, special," <<
  std::endl << "   incidental, or consequential damages of any character arising as a" <<
  std::endl << "   result of this License or out of the use or inability to use the" <<
  std::endl << "   Work (including but not limited to damages for loss of goodwill," <<
  std::endl << "   work stoppage, computer failure or malfunction, or any and all" <<
  std::endl << "   other commercial damages or losses), even if such Contributor" <<
  std::endl << "   has been advised of the possibility of such damages." <<
  std::endl << std::endl;
              // vvv 80 character width vvv
              /*12345678901234567890123456789012345678901234567890123456789012345678901234567890*/
  std::cout << "                            ====== Agreement ======                             " <<
  std::endl << "If, AND ONLY IF, you have read and understood the above notices, AND you have" <<
  std::endl << "considered and accepted the risks inherent in running this software, you may" <<
  std::endl << "modify 'conf.json' file to change the value of 'agreement_accept'" <<
  std::endl << "from false to true." <<
  std::endl << "Doing so licenses your use of this software under the above terms, and will" <<
  std::endl << "unlock the software for use." <<
  std::endl;
  
  
  
}
