name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make web server
      
  run:
  
    runs-on: ubuntu-latest
      
    steps:
    - name: Run frontend
      run: cd build/web; python3 -m http.server && cd ../..
      
    - name: Run backend
      run: cd build/server; sed -i 's/false/true/g' conf.json; ./rc2serve; cd ../..
